import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

// import Framer Motion
import { motion } from 'framer-motion'

// import styled 
import styled from 'styled-components'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    
        
        

    
    </>
  )
}

{/*
// if i decide to use an svg
 <div className="logo">
  <Image
  style={{backgroundColor: "green"}}
    className="logo"
    src="/next.svg"
    alt="Next.js Logo"
    width={180}
    height={37}
    priority
  />
  <div className="thirteen">
    <Image
      src="/thirteen.svg"
      alt="13"
      width={40}
      height={31}
      priority
    />
  </div>
</div>   */}